### ISSUE TITLE
Removing color from stoplights

### ISSUE THREAD

**Issue by saadq** [zpnk/hyper-apex#1]
How did you dim out the maximize/minimize/close buttons? This is what it looks like for me: 

![screen shot 2016-12-23 at 11 35 43 pm](https://cloud.githubusercontent.com/assets/5678694/21465244/88a1adb8-c968-11e6-9c96-3014f185d6ca.png)

**Comment by zpnk** [comment]
Hey @saadq! That is actually a MacOS setting. You can find it in System Preferences -> General.

Thanks for asking about it, I will probably add a note in the readme. Hope you are enjoying the theme!

![system preferences](https://cloud.githubusercontent.com/assets/3493970/21466108/e21f52ba-c971-11e6-8973-1d79c451a54e.png)

**Comment by saadq** [comment]
Ah okay, thanks for the quick reply!
